/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.table.*;
import java.util.Objects;
import javax.swing.DefaultComboBoxModel;
import java.io.IOException;
import java.util.Objects;
import javax.swing.JTable;

/**
 *
 * @author Andrei
 */
public class CatalogGUI extends javax.swing.JFrame {
    public Catalog catalog;

    /**
     * Creates new form CatalogGUI
     */
    public CatalogGUI() {
        initComponents();
    }
    
    public CatalogGUI(Catalog catalog) {
        this.catalog = catalog;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStudenti = new javax.swing.JTable();
        jButtonAdaugaStudent = new javax.swing.JButton();
        jTextFieldNume = new javax.swing.JTextField();
        jLabelNume = new javax.swing.JLabel();
        jLabelPrenume = new javax.swing.JLabel();
        jTextFieldPrenume = new javax.swing.JTextField();
        jLabelVarsta = new javax.swing.JLabel();
        jTextFieldVarsta = new javax.swing.JTextField();
        jTextFieldCNP = new javax.swing.JTextField();
        jLabelCNP = new javax.swing.JLabel();
        jLabelJudet = new javax.swing.JLabel();
        jLabelOras = new javax.swing.JLabel();
        jLabelTelefon = new javax.swing.JLabel();
        jLabelStrada = new javax.swing.JLabel();
        jTextFieldStrada = new javax.swing.JTextField();
        jLabelNr = new javax.swing.JLabel();
        jTextFieldNr = new javax.swing.JTextField();
        jLabelCodPostal = new javax.swing.JLabel();
        jTextFieldCodPostal = new javax.swing.JTextField();
        jTextFieldTelefon = new javax.swing.JTextField();
        jTextFieldOras = new javax.swing.JTextField();
        jTextFieldJudet = new javax.swing.JTextField();
        jComboBoxFacultate = new javax.swing.JComboBox<>();
        jLabelFacultate = new javax.swing.JLabel();
        jLabelSpecializare = new javax.swing.JLabel();
        jComboBoxSpecializare = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDetalii = new javax.swing.JTextArea();
        jLabelMaterie1 = new javax.swing.JLabel();
        jLabelMaterie2 = new javax.swing.JLabel();
        jLabelMaterie3 = new javax.swing.JLabel();
        jTextFieldMaterie1 = new javax.swing.JTextField();
        jTextFieldMaterie2 = new javax.swing.JTextField();
        jTextFieldMaterie3 = new javax.swing.JTextField();
        jButtonSalveazaNotele = new javax.swing.JButton();
        jCheckBoxNote = new javax.swing.JCheckBox();
        jButtonAplicaFiltrele = new javax.swing.JButton();
        jCheckBoxFiltruOras = new javax.swing.JCheckBox();
        jCheckBoxFiltruFacultate = new javax.swing.JCheckBox();
        jCheckBoxFiltruSpecializare = new javax.swing.JCheckBox();
        jComboBoxFiltruFacultate = new javax.swing.JComboBox<>();
        jComboBoxFiltruSpecializare = new javax.swing.JComboBox<>();
        jComboBoxFiltruOras = new javax.swing.JComboBox<>();
        jButtonCitire = new javax.swing.JButton();
        jButtonScriere = new javax.swing.JButton();
        jButtonStergere = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableStudenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nr. matricol", "Nume", "Prenume", "Facultate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableStudenti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableStudentiMouseClicked(evt);
            }
        });
        jTableStudenti.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTableStudentiPropertyChange(evt);
            }
        });
        // Adauga in tabel studentii deja existenti
        Student stud= new Student();
        for (int i=0;i<this.catalog.studenti.size();i++){
            stud = this.catalog.studenti.get(i);
            Object[] row = { stud.nrMatricol, stud.nume, stud.prenume , stud.facultate.nume };
            DefaultTableModel model = (DefaultTableModel) jTableStudenti.getModel();
            model.addRow(row);
        }
        jScrollPane1.setViewportView(jTableStudenti);

        jButtonAdaugaStudent.setText("Adauga Student");
        jButtonAdaugaStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdaugaStudentActionPerformed(evt);
            }
        });

        jTextFieldNume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeActionPerformed(evt);
            }
        });

        jLabelNume.setText("Nume");

        jLabelPrenume.setText("Prenume");

        jTextFieldPrenume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrenumeActionPerformed(evt);
            }
        });

        jLabelVarsta.setText("Varsta");

        jTextFieldVarsta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVarstaActionPerformed(evt);
            }
        });

        jLabelCNP.setText("CNP");

        jLabelJudet.setText("Judet");

        jLabelOras.setText("Oras");

        jLabelTelefon.setText("Telefon");

        jLabelStrada.setText("Strada");

        jLabelNr.setText("nr.");

        jLabelCodPostal.setText("Cod postal");

        ArrayList<String> listaNumeFacultati = new ArrayList<String>();
        for (int i = 0; i < this.catalog.facultati.size(); i++) {
            listaNumeFacultati.add(this.catalog.facultati.get(i).nume);
        }
        String[] StringArrayFacultati = listaNumeFacultati.toArray(new String[0]);
        jComboBoxFacultate.setModel(new javax.swing.DefaultComboBoxModel<>(StringArrayFacultati));
        jComboBoxFacultate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFacultateActionPerformed(evt);
            }
        });

        jLabelFacultate.setText("Facultate");

        jLabelSpecializare.setText("Specializare");

        ArrayList<String> listaNumeSpecializari = new ArrayList<String>();

        String facultateDeCautat = jComboBoxFacultate.getSelectedItem().toString();
        int ok=0;
        while(ok==0){
            for (int i = 0; i < this.catalog.facultati.size(); i++) {
                if (facultateDeCautat==this.catalog.facultati.get(i).nume){
                    ok=1;
                    for (int j=0;j<this.catalog.facultati.get(i).specializari.size();j++){
                        listaNumeSpecializari.add(this.catalog.facultati.get(i).specializari.get(j).nume);
                    }
                }
            }
        }

        String[] StringArraySpecializari = listaNumeSpecializari.toArray(new String[0]);
        jComboBoxSpecializare.setModel(new javax.swing.DefaultComboBoxModel<>(StringArraySpecializari));

        jTextAreaDetalii.setColumns(20);
        jTextAreaDetalii.setRows(5);
        jScrollPane2.setViewportView(jTextAreaDetalii);

        jLabelMaterie1.setText("Nespecificat");

        jLabelMaterie2.setText("Nespecificat");

        jLabelMaterie3.setText("Nespecificat");

        jTextFieldMaterie1.setText("       -");

        jTextFieldMaterie2.setText("       -");

        jTextFieldMaterie3.setText("       -");

        jButtonSalveazaNotele.setText("Salveaza notele");
        jButtonSalveazaNotele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalveazaNoteleActionPerformed(evt);
            }
        });

        jCheckBoxNote.setText("Arata doar studentii integralisti");

        jButtonAplicaFiltrele.setText("Aplica filtrele");
        jButtonAplicaFiltrele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAplicaFiltreleActionPerformed(evt);
            }
        });

        jCheckBoxFiltruOras.setText("Arata doar studentii cu resedinta in");
        jCheckBoxFiltruOras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFiltruOrasActionPerformed(evt);
            }
        });

        jCheckBoxFiltruFacultate.setText("Arata doar studentii de la facultatea");
        jCheckBoxFiltruFacultate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFiltruFacultateActionPerformed(evt);
            }
        });

        jCheckBoxFiltruSpecializare.setText("Arata doar studentii de la specializarea");
        jCheckBoxFiltruSpecializare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFiltruSpecializareActionPerformed(evt);
            }
        });

        jComboBoxFiltruFacultate.setModel(new javax.swing.DefaultComboBoxModel<>(StringArrayFacultati));
        jComboBoxFiltruFacultate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFiltruFacultateActionPerformed(evt);
            }
        });

        ArrayList<String> listaSpecializariTotal = new ArrayList<String>();
        for (int i=0;i<this.catalog.facultati.size();i++){
            for (int j=0;j<this.catalog.facultati.get(i).specializari.size();j++){
                listaSpecializariTotal.add(this.catalog.facultati.get(i).specializari.get(j).nume);
            }
        }
        String[] StringArraySpecializariTotal = listaSpecializariTotal.toArray(new String[0]);
        jComboBoxFiltruSpecializare.setModel(new javax.swing.DefaultComboBoxModel<>(StringArraySpecializariTotal));

        String[] StringArrayOrase = this.catalog.orase.toArray(new String[0]);
        jComboBoxFiltruOras.setModel(new javax.swing.DefaultComboBoxModel<>(StringArrayOrase));
        jComboBoxFiltruOras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFiltruOrasActionPerformed(evt);
            }
        });

        jButtonCitire.setText("Citeste date din fisier");
        jButtonCitire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCitireActionPerformed(evt);
            }
        });

        jButtonScriere.setText("Scrie date in fisier");
        jButtonScriere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonScriereActionPerformed(evt);
            }
        });

        jButtonStergere.setText("Sterge Student");
        jButtonStergere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStergereActionPerformed(evt);
            }
        });

        jButton1.setText("Adauga Student Generat Aleatoriu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelMaterie1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(jLabelMaterie2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelMaterie3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldMaterie2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldMaterie1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldMaterie3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonScriere, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(68, 68, 68)
                                    .addComponent(jButtonSalveazaNotele))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(50, 50, 50)
                                    .addComponent(jButtonCitire))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNume, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelVarsta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelCNP, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelOras, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelPrenume, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelJudet, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelStrada, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabelTelefon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelCodPostal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelFacultate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabelSpecializare, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldTelefon, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldJudet, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCNP, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldVarsta, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPrenume, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNume, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldOras, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCodPostal, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxSpecializare, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxFacultate, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jTextFieldStrada, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelNr, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldNr, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(76, 76, 76))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(194, 194, 194)
                                        .addComponent(jButton1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(236, 236, 236)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButtonAdaugaStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonStergere, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(258, 258, 258)
                                .addComponent(jButtonAplicaFiltrele, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxFiltruSpecializare, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBoxFiltruFacultate)
                                    .addComponent(jCheckBoxFiltruOras)
                                    .addComponent(jCheckBoxNote))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxFiltruFacultate, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxFiltruSpecializare, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxFiltruOras, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 73, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNume))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPrenume)
                            .addComponent(jTextFieldPrenume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelVarsta)
                            .addComponent(jTextFieldVarsta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCNP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCNP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelJudet)
                            .addComponent(jTextFieldJudet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldOras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelOras))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTelefon)
                            .addComponent(jTextFieldTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelStrada)
                            .addComponent(jTextFieldStrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNr)
                            .addComponent(jTextFieldNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCodPostal)
                            .addComponent(jTextFieldCodPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxFacultate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFacultate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxSpecializare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSpecializare))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAdaugaStudent)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonStergere)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(jCheckBoxNote)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxFiltruOras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxFiltruOras))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxFiltruFacultate)
                            .addComponent(jComboBoxFiltruFacultate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxFiltruSpecializare)
                            .addComponent(jComboBoxFiltruSpecializare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAplicaFiltrele))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelMaterie1)
                                    .addComponent(jTextFieldMaterie1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelMaterie2)
                                    .addComponent(jTextFieldMaterie2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelMaterie3)
                                    .addComponent(jTextFieldMaterie3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSalveazaNotele)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonScriere)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCitire)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdaugaStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdaugaStudentActionPerformed
        // TODO add your handling code here:
        Facultate fac = new Facultate();
        Specializare spec = new Specializare();
        String NumeFacultateDeCautat = jComboBoxFacultate.getSelectedItem().toString();
        String NumeSpecializareDeCautat = jComboBoxSpecializare.getSelectedItem().toString();
        for (int i=0;i< this.catalog.facultati.size();i++){
            if (NumeFacultateDeCautat==this.catalog.facultati.get(i).nume){
                fac=this.catalog.facultati.get(i);
                for (int j=0;j<this.catalog.facultati.get(i).specializari.size();j++){
                    if (NumeSpecializareDeCautat==this.catalog.facultati.get(i).specializari.get(j).nume){
                        spec=this.catalog.facultati.get(i).specializari.get(j);
                    }
                }
            }
        }
        Student stud=new Student (Integer.parseInt(jTextFieldVarsta.getText()),jTextFieldNume.getText(),jTextFieldPrenume.getText(),jTextFieldCNP.getText(), jTextFieldJudet.getText(),jTextFieldOras.getText(),jTextFieldStrada.getText(),Integer.parseInt(jTextFieldNr.getText()),Integer.parseInt(jTextFieldCodPostal.getText()),jTextFieldTelefon.getText(),fac,spec);
        this.catalog.adaugaStudent(stud);

        Object[] row = { stud.nrMatricol, stud.nume, stud.prenume , stud.facultate.nume };

        DefaultTableModel model = (DefaultTableModel) jTableStudenti.getModel();

        model.addRow(row);
        
        DefaultComboBoxModel<String> model2 = new DefaultComboBoxModel<>(this.catalog.orase.toArray(new String[0]));
        jComboBoxFiltruOras.setModel(model2);
        
    }//GEN-LAST:event_jButtonAdaugaStudentActionPerformed

    private void jTextFieldNumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeActionPerformed

    private void jTextFieldPrenumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrenumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrenumeActionPerformed

    private void jComboBoxFacultateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFacultateActionPerformed
        // TODO add your handling code here:
        ArrayList<String> listaNumeSpecializari = new ArrayList<String>();

        String facultateDeCautat = this.jComboBoxFacultate.getSelectedItem().toString();
        int ok=0;
        while(ok==0){
            for (int i = 0; i < this.catalog.facultati.size(); i++) {
                if (facultateDeCautat==this.catalog.facultati.get(i).nume){
                    ok=1;
                    for (int j=0;j<this.catalog.facultati.get(i).specializari.size();j++){
                        listaNumeSpecializari.add(this.catalog.facultati.get(i).specializari.get(j).nume);
                    }
                }
            }
        }

        String[] StringArraySpecializari = listaNumeSpecializari.toArray(new String[0]);
        jComboBoxSpecializare.setModel(new javax.swing.DefaultComboBoxModel<>(StringArraySpecializari));
        
    }//GEN-LAST:event_jComboBoxFacultateActionPerformed

    private void jTextFieldVarstaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVarstaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldVarstaActionPerformed

    private void jTableStudentiPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTableStudentiPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableStudentiPropertyChange

    private void jTableStudentiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableStudentiMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTableStudenti.getModel();
        int column = 0;
        int row = jTableStudenti.getSelectedRow();
        int nrMatricolDeCautat = Integer.parseInt(model.getValueAt(row, 0).toString());
        for (int i=0;i<this.catalog.studenti.size();i++){
            if (this.catalog.studenti.get(i).nrMatricol==nrMatricolDeCautat){
                
                this.jTextAreaDetalii.setText(this.catalog.studenti.get(i).toStringfaranote());
                jLabelMaterie1.setText(this.catalog.studenti.get(i).specializare.materii.get(0).nume);
                jLabelMaterie2.setText(this.catalog.studenti.get(i).specializare.materii.get(1).nume);
                jLabelMaterie3.setText(this.catalog.studenti.get(i).specializare.materii.get(2).nume);
                jTextFieldMaterie1.setText(Integer.toString(this.catalog.studenti.get(i).note.get(this.catalog.studenti.get(i).specializare.materii.get(0))));
                jTextFieldMaterie2.setText(Integer.toString(this.catalog.studenti.get(i).note.get(this.catalog.studenti.get(i).specializare.materii.get(1))));
                jTextFieldMaterie3.setText(Integer.toString(this.catalog.studenti.get(i).note.get(this.catalog.studenti.get(i).specializare.materii.get(2))));
            }
        }
    }//GEN-LAST:event_jTableStudentiMouseClicked

    private void jButtonSalveazaNoteleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalveazaNoteleActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTableStudenti.getModel();
        int column = 0;
        int row = jTableStudenti.getSelectedRow();
        int nrMatricolDeCautat = Integer.parseInt(model.getValueAt(row, 0).toString());
        for (int i=0;i<this.catalog.studenti.size();i++){
            if (this.catalog.studenti.get(i).nrMatricol==nrMatricolDeCautat){
                
                this.catalog.studenti.get(i).note.put(this.catalog.studenti.get(i).specializare.materii.get(0), Integer.parseInt(jTextFieldMaterie1.getText()));
                this.catalog.studenti.get(i).note.put(this.catalog.studenti.get(i).specializare.materii.get(1), Integer.parseInt(jTextFieldMaterie2.getText()));
                this.catalog.studenti.get(i).note.put(this.catalog.studenti.get(i).specializare.materii.get(2), Integer.parseInt(jTextFieldMaterie3.getText()));
            }
        }
    }//GEN-LAST:event_jButtonSalveazaNoteleActionPerformed

    private void jButtonAplicaFiltreleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAplicaFiltreleActionPerformed
        // TODO add your handling code here:
        ArrayList<Student> studentiFiltrati = this.catalog.studenti;
        if (jCheckBoxNote.isSelected()){
            studentiFiltrati=this.catalog.filtruNote(studentiFiltrati);
        }
        
        if (jCheckBoxFiltruOras.isSelected()){
            studentiFiltrati=this.catalog.filtruOras(jComboBoxFiltruOras.getSelectedItem().toString(),studentiFiltrati);
        }
        
        if (jCheckBoxFiltruSpecializare.isSelected()){
            studentiFiltrati=this.catalog.filtruSpecializare(jComboBoxFiltruSpecializare.getSelectedItem().toString(),studentiFiltrati);
        }
        
        if (jCheckBoxFiltruFacultate.isSelected()){
            studentiFiltrati=this.catalog.filtruFacultate(jComboBoxFiltruFacultate.getSelectedItem().toString(),studentiFiltrati);
        }
        // terminat filtrarea, umplem tabelul
        Student stud= new Student();
        DefaultTableModel model = (DefaultTableModel) jTableStudenti.getModel();
        model.setRowCount(0);
        for (int i=0;i<studentiFiltrati.size();i++){
            stud = studentiFiltrati.get(i);
            Object[] row = { stud.nrMatricol, stud.nume, stud.prenume , stud.facultate.nume };
            model.addRow(row);
        }
    }//GEN-LAST:event_jButtonAplicaFiltreleActionPerformed

    private void jCheckBoxFiltruOrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFiltruOrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxFiltruOrasActionPerformed

    private void jCheckBoxFiltruFacultateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFiltruFacultateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxFiltruFacultateActionPerformed

    private void jCheckBoxFiltruSpecializareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFiltruSpecializareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxFiltruSpecializareActionPerformed

    private void jComboBoxFiltruFacultateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFiltruFacultateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFiltruFacultateActionPerformed

    private void jComboBoxFiltruOrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFiltruOrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFiltruOrasActionPerformed

    private void jButtonCitireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCitireActionPerformed
        // TODO add your handling code here:
        try{
        this.catalog=this.catalog.CitesteFisier();
        } catch (Exception e){
            System.out.println("Eroare citire");
        }
        DefaultTableModel model = (DefaultTableModel) jTableStudenti.getModel();
        Student stud= new Student();
        model.setRowCount(0);
        for (int i=0;i<this.catalog.studenti.size();i++){
            stud = this.catalog.studenti.get(i);
            Object[] row = { stud.nrMatricol, stud.nume, stud.prenume , stud.facultate.nume };
            model.addRow(row);
        }
    }//GEN-LAST:event_jButtonCitireActionPerformed

    private void jButtonScriereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonScriereActionPerformed
        // TODO add your handling code here:
        try{
        this.catalog.ScrieFisier(this.catalog);
        } catch (Exception e){
            System.out.println("Eroare scriere");
        }
    }//GEN-LAST:event_jButtonScriereActionPerformed

    private void jButtonStergereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStergereActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTableStudenti.getModel();
        int column = 0;
        if (Objects.isNull(jTableStudenti.getSelectedRow())){
            return;
        }
        if (jTableStudenti.getSelectedRow()==-1){
            return;
        }
        int row = jTableStudenti.getSelectedRow();
        int nrMatricolDeCautat = Integer.parseInt(model.getValueAt(row, 0).toString());
        for (int i=0;i<this.catalog.studenti.size();i++){
            if (this.catalog.studenti.get(i).nrMatricol==nrMatricolDeCautat){
                
                this.catalog.studenti.remove(this.catalog.studenti.get(i));
            }
        }            
        model.removeRow(jTableStudenti.getSelectedRow());
    }//GEN-LAST:event_jButtonStergereActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Student stud=this.catalog.GenereazaStudentAleatoriu();
        Object[] row = { stud.nrMatricol, stud.nume, stud.prenume , stud.facultate.nume };

        DefaultTableModel model = (DefaultTableModel) jTableStudenti.getModel();

        model.addRow(row);
        DefaultComboBoxModel<String> model2 = new DefaultComboBoxModel<>(this.catalog.orase.toArray(new String[0]));
        jComboBoxFiltruOras.setModel(model2);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatalogGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatalogGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatalogGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatalogGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CatalogGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAdaugaStudent;
    private javax.swing.JButton jButtonAplicaFiltrele;
    private javax.swing.JButton jButtonCitire;
    private javax.swing.JButton jButtonSalveazaNotele;
    private javax.swing.JButton jButtonScriere;
    private javax.swing.JButton jButtonStergere;
    private javax.swing.JCheckBox jCheckBoxFiltruFacultate;
    private javax.swing.JCheckBox jCheckBoxFiltruOras;
    private javax.swing.JCheckBox jCheckBoxFiltruSpecializare;
    private javax.swing.JCheckBox jCheckBoxNote;
    private javax.swing.JComboBox<String> jComboBoxFacultate;
    private javax.swing.JComboBox<String> jComboBoxFiltruFacultate;
    private javax.swing.JComboBox<String> jComboBoxFiltruOras;
    private javax.swing.JComboBox<String> jComboBoxFiltruSpecializare;
    private javax.swing.JComboBox<String> jComboBoxSpecializare;
    private javax.swing.JLabel jLabelCNP;
    private javax.swing.JLabel jLabelCodPostal;
    private javax.swing.JLabel jLabelFacultate;
    private javax.swing.JLabel jLabelJudet;
    private javax.swing.JLabel jLabelMaterie1;
    private javax.swing.JLabel jLabelMaterie2;
    private javax.swing.JLabel jLabelMaterie3;
    private javax.swing.JLabel jLabelNr;
    private javax.swing.JLabel jLabelNume;
    private javax.swing.JLabel jLabelOras;
    private javax.swing.JLabel jLabelPrenume;
    private javax.swing.JLabel jLabelSpecializare;
    private javax.swing.JLabel jLabelStrada;
    private javax.swing.JLabel jLabelTelefon;
    private javax.swing.JLabel jLabelVarsta;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableStudenti;
    private javax.swing.JTextArea jTextAreaDetalii;
    private javax.swing.JTextField jTextFieldCNP;
    private javax.swing.JTextField jTextFieldCodPostal;
    private javax.swing.JTextField jTextFieldJudet;
    private javax.swing.JTextField jTextFieldMaterie1;
    private javax.swing.JTextField jTextFieldMaterie2;
    private javax.swing.JTextField jTextFieldMaterie3;
    private javax.swing.JTextField jTextFieldNr;
    private javax.swing.JTextField jTextFieldNume;
    private javax.swing.JTextField jTextFieldOras;
    private javax.swing.JTextField jTextFieldPrenume;
    private javax.swing.JTextField jTextFieldStrada;
    private javax.swing.JTextField jTextFieldTelefon;
    private javax.swing.JTextField jTextFieldVarsta;
    // End of variables declaration//GEN-END:variables
}
