/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.util.ArrayList;
import javax.swing.table.*;

/**
 *
 * @author Andrei
 */
public class CatalogGUI extends javax.swing.JFrame {
    public Catalog catalog;

    /**
     * Creates new form CatalogGUI
     */
    public CatalogGUI() {
        initComponents();
    }
    
    public CatalogGUI(Catalog catalog) {
        this.catalog = catalog;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStudenti = new javax.swing.JTable();
        jButtonAdaugaStudent = new javax.swing.JButton();
        jTextFieldNume = new javax.swing.JTextField();
        jLabelNume = new javax.swing.JLabel();
        jLabelPrenume = new javax.swing.JLabel();
        jTextFieldPrenume = new javax.swing.JTextField();
        jLabelVarsta = new javax.swing.JLabel();
        jTextFieldVarsta = new javax.swing.JTextField();
        jTextFieldCNP = new javax.swing.JTextField();
        jLabelCNP = new javax.swing.JLabel();
        jLabelJudet = new javax.swing.JLabel();
        jLabelOras = new javax.swing.JLabel();
        jLabelTelefon = new javax.swing.JLabel();
        jLabelStrada = new javax.swing.JLabel();
        jTextFieldStrada = new javax.swing.JTextField();
        jLabelNr = new javax.swing.JLabel();
        jTextFieldNr = new javax.swing.JTextField();
        jLabelCodPostal = new javax.swing.JLabel();
        jTextFieldCodPostal = new javax.swing.JTextField();
        jTextFieldTelefon = new javax.swing.JTextField();
        jTextFieldOras = new javax.swing.JTextField();
        jTextFieldJudet = new javax.swing.JTextField();
        jComboBoxFacultate = new javax.swing.JComboBox<>();
        jLabelFacultate = new javax.swing.JLabel();
        jLabelSpecializare = new javax.swing.JLabel();
        jComboBoxSpecializare = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDetalii = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableStudenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nr. matricol", "Nume", "Prenume", "Facultate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableStudenti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableStudentiMouseClicked(evt);
            }
        });
        jTableStudenti.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTableStudentiPropertyChange(evt);
            }
        });
        // Adauga in tabel studentii deja existenti
        Student stud= new Student();
        for (int i=0;i<this.catalog.studenti.size();i++){
            stud = this.catalog.studenti.get(i);
            Object[] row = { stud.nrMatricol, stud.nume, stud.prenume , stud.facultate.nume };
            DefaultTableModel model = (DefaultTableModel) jTableStudenti.getModel();
            model.addRow(row);
        }
        jScrollPane1.setViewportView(jTableStudenti);

        jButtonAdaugaStudent.setText("Adauga Student");
        jButtonAdaugaStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdaugaStudentActionPerformed(evt);
            }
        });

        jTextFieldNume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeActionPerformed(evt);
            }
        });

        jLabelNume.setText("Nume");

        jLabelPrenume.setText("Prenume");

        jTextFieldPrenume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrenumeActionPerformed(evt);
            }
        });

        jLabelVarsta.setText("Varsta");

        jTextFieldVarsta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVarstaActionPerformed(evt);
            }
        });

        jLabelCNP.setText("CNP");

        jLabelJudet.setText("Judet");

        jLabelOras.setText("Oras");

        jLabelTelefon.setText("Telefon");

        jLabelStrada.setText("Strada");

        jLabelNr.setText("nr.");

        jLabelCodPostal.setText("Cod postal");

        ArrayList<String> listaNumeFacultati = new ArrayList<String>();
        for (int i = 0; i < this.catalog.facultati.size(); i++) {
            listaNumeFacultati.add(this.catalog.facultati.get(i).nume);
        }
        String[] StringArrayFacultati = listaNumeFacultati.toArray(new String[0]);
        jComboBoxFacultate.setModel(new javax.swing.DefaultComboBoxModel<>(StringArrayFacultati));
        jComboBoxFacultate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFacultateActionPerformed(evt);
            }
        });

        jLabelFacultate.setText("Facultate");

        jLabelSpecializare.setText("Specializare");

        ArrayList<String> listaNumeSpecializari = new ArrayList<String>();

        String facultateDeCautat = jComboBoxFacultate.getSelectedItem().toString();
        int ok=0;
        while(ok==0){
            for (int i = 0; i < this.catalog.facultati.size(); i++) {
                if (facultateDeCautat==this.catalog.facultati.get(i).nume){
                    ok=1;
                    for (int j=0;j<this.catalog.facultati.get(i).specializari.size();j++){
                        listaNumeSpecializari.add(this.catalog.facultati.get(i).specializari.get(j).nume);
                    }
                }
            }
        }

        String[] StringArraySpecializari = listaNumeSpecializari.toArray(new String[0]);
        jComboBoxSpecializare.setModel(new javax.swing.DefaultComboBoxModel<>(StringArraySpecializari));

        jTextAreaDetalii.setColumns(20);
        jTextAreaDetalii.setRows(5);
        jScrollPane2.setViewportView(jTextAreaDetalii);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelNume, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelVarsta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelCNP, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelOras, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelStrada, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelPrenume, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelJudet, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(51, 51, 51)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextFieldPrenume, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextFieldNume, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextFieldVarsta, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextFieldCNP, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldStrada, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(7, 7, 7)
                                            .addComponent(jTextFieldOras, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextFieldJudet, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabelTelefon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelCodPostal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelFacultate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldCodPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBoxFacultate, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelSpecializare, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBoxSpecializare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNr, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jButtonAdaugaStudent)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNume))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPrenume)
                            .addComponent(jTextFieldPrenume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelVarsta)
                            .addComponent(jTextFieldVarsta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCNP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCNP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelJudet)
                            .addComponent(jTextFieldJudet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelOras)
                            .addComponent(jTextFieldOras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTelefon)
                            .addComponent(jTextFieldTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelStrada)
                            .addComponent(jTextFieldStrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNr)
                            .addComponent(jTextFieldNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCodPostal)
                            .addComponent(jTextFieldCodPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxFacultate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFacultate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSpecializare)
                            .addComponent(jComboBoxSpecializare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAdaugaStudent))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdaugaStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdaugaStudentActionPerformed
        // TODO add your handling code here:
        Facultate fac = new Facultate();
        Specializare spec = new Specializare();
        String NumeFacultateDeCautat = jComboBoxFacultate.getSelectedItem().toString();
        String NumeSpecializareDeCautat = jComboBoxSpecializare.getSelectedItem().toString();
        for (int i=0;i< this.catalog.facultati.size();i++){
            if (NumeFacultateDeCautat==this.catalog.facultati.get(i).nume){
                fac=this.catalog.facultati.get(i);
                for (int j=0;j<this.catalog.facultati.get(i).specializari.size();j++){
                    if (NumeSpecializareDeCautat==this.catalog.facultati.get(i).specializari.get(j).nume){
                        spec=this.catalog.facultati.get(i).specializari.get(j);
                    }
                }
            }
        }
        Student stud=new Student (Integer.parseInt(jTextFieldVarsta.getText()),jTextFieldNume.getText(),jTextFieldPrenume.getText(),jTextFieldCNP.getText(), jTextFieldJudet.getText(),jTextFieldOras.getText(),jTextFieldStrada.getText(),Integer.parseInt(jTextFieldNr.getText()),Integer.parseInt(jTextFieldCodPostal.getText()),jTextFieldTelefon.getText(),fac,spec);
        this.catalog.adaugaStudent(stud);

        Object[] row = { stud.nrMatricol, stud.nume, stud.prenume , stud.facultate.nume };

        DefaultTableModel model = (DefaultTableModel) jTableStudenti.getModel();

        model.addRow(row);
        
    }//GEN-LAST:event_jButtonAdaugaStudentActionPerformed

    private void jTextFieldNumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeActionPerformed

    private void jTextFieldPrenumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrenumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrenumeActionPerformed

    private void jComboBoxFacultateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFacultateActionPerformed
        // TODO add your handling code here:
        ArrayList<String> listaNumeSpecializari = new ArrayList<String>();

        String facultateDeCautat = this.jComboBoxFacultate.getSelectedItem().toString();
        int ok=0;
        while(ok==0){
            for (int i = 0; i < this.catalog.facultati.size(); i++) {
                if (facultateDeCautat==this.catalog.facultati.get(i).nume){
                    ok=1;
                    for (int j=0;j<this.catalog.facultati.get(i).specializari.size();j++){
                        listaNumeSpecializari.add(this.catalog.facultati.get(i).specializari.get(j).nume);
                    }
                }
            }
        }

        String[] StringArraySpecializari = listaNumeSpecializari.toArray(new String[0]);
        jComboBoxSpecializare.setModel(new javax.swing.DefaultComboBoxModel<>(StringArraySpecializari));
        
    }//GEN-LAST:event_jComboBoxFacultateActionPerformed

    private void jTextFieldVarstaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVarstaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldVarstaActionPerformed

    private void jTableStudentiPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTableStudentiPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableStudentiPropertyChange

    private void jTableStudentiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableStudentiMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTableStudenti.getModel();
        int column = 0;
        int row = jTableStudenti.getSelectedRow();
        int nrMatricolDeCautat = Integer.parseInt(model.getValueAt(row, 0).toString());
        for (int i=0;i<this.catalog.studenti.size();i++){
            if (this.catalog.studenti.get(i).nrMatricol==nrMatricolDeCautat){
                this.jTextAreaDetalii = new javax.swing.JTextArea("Nume: "+this.catalog.studenti.get(i).nume);
            }
        }
    }//GEN-LAST:event_jTableStudentiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatalogGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatalogGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatalogGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatalogGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CatalogGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdaugaStudent;
    private javax.swing.JComboBox<String> jComboBoxFacultate;
    private javax.swing.JComboBox<String> jComboBoxSpecializare;
    private javax.swing.JLabel jLabelCNP;
    private javax.swing.JLabel jLabelCodPostal;
    private javax.swing.JLabel jLabelFacultate;
    private javax.swing.JLabel jLabelJudet;
    private javax.swing.JLabel jLabelNr;
    private javax.swing.JLabel jLabelNume;
    private javax.swing.JLabel jLabelOras;
    private javax.swing.JLabel jLabelPrenume;
    private javax.swing.JLabel jLabelSpecializare;
    private javax.swing.JLabel jLabelStrada;
    private javax.swing.JLabel jLabelTelefon;
    private javax.swing.JLabel jLabelVarsta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableStudenti;
    private javax.swing.JTextArea jTextAreaDetalii;
    private javax.swing.JTextField jTextFieldCNP;
    private javax.swing.JTextField jTextFieldCodPostal;
    private javax.swing.JTextField jTextFieldJudet;
    private javax.swing.JTextField jTextFieldNr;
    private javax.swing.JTextField jTextFieldNume;
    private javax.swing.JTextField jTextFieldOras;
    private javax.swing.JTextField jTextFieldPrenume;
    private javax.swing.JTextField jTextFieldStrada;
    private javax.swing.JTextField jTextFieldTelefon;
    private javax.swing.JTextField jTextFieldVarsta;
    // End of variables declaration//GEN-END:variables
}
